#+PROPERTY: header-args :comments link

* emacs configuration
  
** configuration reload helper
   
   `C-x C-l`: reload this file.

#+BEGIN_SRC emacs-lisp
  (defun reload-config ()
    (interactive)
    (load-file user-init-file)
    (princ "Configuration reloaded."))

  (global-set-key (kbd "C-x C-l") 'reload-config)
#+END_SRC

** specpdl and eval depth size

   Bump them up so we avoid issues with some LSP providers:
   
#+BEGIN_SRC emacs-lisp
    (setq max-specpdl-size 500
	  max-lisp-eval-depth 1000)
#+END_SRC

** key bindings for OSX

   Set up modifiers to be consistent on OSX with the emacs-mac tapped version of emacs

#+BEGIN_SRC emacs-lisp
  (when (eq system-type 'darwin)
    (setq
     frame-resize-pixelwise t
     menu-bar-mode t
     mac-command-modifier 'super
     mac-option-modifier 'meta
     mac-control-modifier 'control))
#+END_SRC

#+RESULTS:
: control

** package management
   
   Package installation is idempotent, using `straight` and `use-package`.

*** repos
    
    Add the GNU, ELPA, MELPA, MELPA-stable, Marmalade and Org repos.
    
#+BEGIN_SRC emacs-lisp
  (setq package-archives '(("gnu" . "http://elpa.gnu.org/packages/")
			   ("elpa" . "http://tromey.com/elpa/")
			   ("melpa" . "http://melpa.org/packages/")
			   ("melpa-stable" . "http://stable.melpa.org/packages/")
			   ("org" . "http://orgmode.org/elpa/")))
#+END_SRC

*** straight
    
    Set up straight for installing and updating packages.

#+BEGIN_SRC emacs-lisp
  (setq straight-repository-branch "develop"
        straight-use-package-by-default t)
  (defvar bootstrap-version)
  (let ((bootstrap-file
	 (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
	(bootstrap-version 5))
    (unless (file-exists-p bootstrap-file)
      (with-current-buffer
	  (url-retrieve-synchronously
	   "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
	   'silent 'inhibit-cookies)
	(goto-char (point-max))
	(eval-print-last-sexp)))
    (load bootstrap-file nil 'nomessage))
#+END_SRC

*** use-package
    
    Set up use-package for organsing package configuration.
    We also configure straight to use use-package to actually install packages.

#+BEGIN_SRC emacs-lisp
  (straight-use-package 'use-package)
  (setq straight-use-package-by-default t)
#+END_SRC

** look 'n feel
*** GUI tweaks   
    
    Disable GUI bits, load the monokai theme, and change the base font.
    Also enables global line mode to highlight the current line.
    
#+BEGIN_SRC emacs-lisp
  (menu-bar-mode -1) (tool-bar-mode -1) (scroll-bar-mode -1)
  (if (eq system-type 'darwin)
    (set-frame-font "Fantasque Sans Mono-14" nil t)
    (set-frame-font "Fantasque Sans Mono-12" nil t))
  (global-hl-line-mode 1)
#+END_SRC

*** theme
    
#+BEGIN_SRC emacs-lisp    
  (use-package gruvbox-theme
    :ensure t
    :config
    (load-theme 'gruvbox t)
    (custom-theme-set-faces
     'gruvbox
     '(org-level-1 ((t (:weight semi-bold :height 2.0))))
     '(org-level-2 ((t (:weight semi-bold :height 1.5))))
     '(org-level-3 ((t (:weight semi-bold :height 1.25))))
     '(org-level-4 ((t (:weight semi-bold :height 1.0)))))
  )
#+END_SRC

*** title line
    
    What to show at the top (window frame) of buffers.

#+BEGIN_SRC emacs-lisp
  (setq frame-title-format
     (list (format "%s %%S: %%j " (system-name))
       '(buffer-file-name "%f" (dired-directory dired-directory "%b"))))
#+END_SRC

** env

   Set environment variables and PATH, as well as loading `exec-env-from-shell` to grab environment variables set by zsh.

#+BEGIN_SRC emacs-lisp
  ;; set the below so tmux knows not to load when we eval .zshrc
  ;; this is respected by ohmyzsh's tmux plugin
  (setenv "EMACS" "1")
  (use-package exec-path-from-shell
    :init
    (when (memq window-system '(mac ns x))
       (exec-path-from-shell-initialize)
  ;; extra environment variables to bring in, in addition to the standard ones like PATH
       (exec-path-from-shell-copy-env "GOPATH")
       (exec-path-from-shell-copy-env "GOBIN")
       (exec-path-from-shell-copy-env "GOFLAGS")))
#+END_SRC

** startup

    Boot into org, with the Org scratch space loaded.
    
#+BEGIN_SRC emacs-lisp
  (setq inhibit-startup-screen t)
  (setq inhibit-splash-screen t)
  (setq initial-major-mode 'org-mode)
  (setq initial-scratch-message nil)

  (if (equal command-line-args '("emacs"))
      (setq initial-buffer-choice "~/Org/scratch.org")
  )
#+END_SRC

** global keybindings

   Some binds and unbinds that I find useful.

#+BEGIN_SRC emacs-lisp
  ;; this was a really fucking annoying, I finally worked out this shortcut was how I was locking up emacs.
  (global-unset-key (kbd "C-z"))
#+END_SRC

** disable backup files

   Yeah, yeah. I'm sure I'll regret this.
#+BEGIN_SRC emacs-lisp
  (setq make-backup-files nil) ; stop creating backup~ files
  (setq auto-save-default nil) ; stop creating #autosave# files  
#+END_SRC

** which key?

   Show possible keybinds as you try desperately top use them.

#+BEGIN_SRC emacs-lisp
  (use-package which-key
    :ensure t)
#+END_SRC

** completion

Add nice autocompletion with ivy

#+BEGIN_SRC emacs-lisp
(use-package counsel
  :after ivy
  :config (counsel-mode))

(use-package ivy
  :defer 0.1
  :diminish
  :bind (("C-c C-r" . ivy-resume)
         ("C-x B" . ivy-switch-buffer-other-window))
  :custom
  (ivy-count-format "(%d/%d) ")
  (ivy-use-virtual-buffers t)
  :config (ivy-mode))

(use-package ivy-rich
  :after ivy)

(use-package swiper
  :after ivy
  :bind (("C-s" . swiper)
         ("C-r" . swiper)))

#+END_SRC

** whitespace

   Ugh, whitespace.

#+BEGIN_SRC emacs-lisp
  (use-package ws-butler
    :ensure t
    :hook (prog-mode . ws-butler-mode))
#+END_SRC

** major modes

   High level additional config for major modes to use.
   Here we map filetypes to major modes, for example.

#+BEGIN_SRC emacs-lisp
  (add-to-list 'auto-mode-alist '("\\.text\\'" . markdown-mode))
  (add-to-list 'auto-mode-alist '("\\.md\\'" . markdown-mode))
  (add-to-list 'auto-mode-alist '("\\.mdown\\'" . markdown-mode))
  (add-to-list 'auto-mode-alist '("\\.markdown\\'" . markdown-mode))
  (add-to-list 'auto-mode-alist '("\\.sh\\'" . shell-script-mode))
  (add-to-list 'auto-mode-alist '("\\.ledger\\'" . hledger-mode))
  (add-to-list 'auto-mode-alist '("\\.adoc\\'" . adoc-mode))
  (add-to-list 'auto-mode-alist '("\\.asciidoc\\'" . adoc-mode))
#+END_SRC

** org mode

   Base configuration for Org Mode

*** use-package

    Start the use-package section for org mode configuration to make sure org is loaded before configuring it.
    
#+BEGIN_SRC emacs-lisp
  (use-package org
	     :config
	   )
#+END_SRC
   
*** org directories

    Set standard directories for Org files.
    
#+BEGIN_SRC emacs-lisp
  (setq org-directory
	(cond
	 ((eq system-type 'darwin)
	  "~/Library/Mobile Documents/com~apple~CloudDocs/Org/")
	 ((eq system-type 'gnu/linux)
	  "~/Org")))  
  (setq org-agenda-files
	(cond
	 ((eq system-type 'darwin)
	  "~/Library/Mobile Documents/com~apple~CloudDocs/Org/")
	 ((eq system-type 'gnu/linux)
	  "~/Org")))  
  (setq org-default-notes-file
	(cond
	 ((eq system-type 'darwin)
	  "~/Library/Mobile Documents/com~apple~CloudDocs/Org/TODO.org")
	 ((eq system-type 'gnu/linux)
	  "~/Org/TODO.org")))
#+END_SRC

*** org shortcut functions
#+BEGIN_SRC emacs-lisp
  (defun org-daily ()
    (interactive)
    (let ((daily-name (format-time-string "%Y-%m-%d")))
      (find-file (expand-file-name (concat org-directory "/Scratch/" daily-name ".org")))))  
  (defun todo ()
    (interactive)
    (find-file (expand-file-name (concat org-directory "/TODO.org"))))
#+END_SRC

*** babel configuration

#+BEGIN_SRC emacs-lisp
  (org-babel-do-load-languages
   'org-babel-load-languages
   '(
     (python . t)
     (shell . t)
     (emacs-lisp . t)
     (awk . t)
     ))

  (setq python-shell-completion-native-enable nil)
  (setq org-latex-minted-options '(("breaklines" "true")
				   ("breakanywhere" "true")))
#+END_SRC

*** extra TODO config

    Add some extra states we can use in TODO lists.
    Also, enable fast selection of TODO state.

#+BEGIN_SRC emacs-lisp
  (setq org-todo-keywords
	(quote ((sequence "TODO(t)"
			  "NEXT(n!)"
			  "WAIT(w!)"
			  "DOING(i!)"
			  "|"
			  "DONE(d!)"
			  ))))

  (setq org-todo-keyword-faces
	(quote (("TODO" :foreground "red" :weight bold)
		("NEXT" :foreground "blue" :weight bold)
		("WAIT" :foreground "orange" :weight bold)
		("DOING" :foreground "orange" :weight bold)
		("DONE" :foreground "forest green" :weight bold)
		)))

  (setq org-use-fast-todo-selection t)
#+END_SRC

*** org TODO dependencies

    Make sure we can't complete items until all child items are complete.
    
#+BEGIN_SRC emacs-lisp
  (setq org-enforce-todo-dependencies t)
#+END_SRC

*** org agenda

    Useful keybinding and window behaviour customisation.

#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "C-c a") 'org-agenda)
  (setq org-agenda-window-setup "current-window")
#+END_SRC

*** org look n' feel

    Change bullet behaviour and look.

#+BEGIN_SRC emacs-lisp
  (setq org-ellipsis " ►"
	org-hide-leading-stars t)
#+END_SRC

** development
*** git

    Set up magit for magic git things.

#+BEGIN_SRC emacs-lisp
(use-package magit
  :bind (("C-x g" . magit-status)
         ("C-x C-g" . magit-status)))
#+END_SRC	 

*** projectile

    Projectile, for dealing with project folders.

#+BEGIN_SRC emacs-lisp
  (use-package projectile
    :ensure t)
#+END_SRC

*** company

    Company, for completion.

#+BEGIN_SRC emacs-lisp
  (use-package company
    :ensure
    :custom
    (company-idle-delay 0.5) ;; how long to wait until popup
    ;; (company-begin-commands nil) ;; uncomment to disable popup
    :bind
    (:map company-active-map
      ("C-n". company-select-next)
      ("C-p". company-select-previous)
      ("M-<". company-select-first)
      ("M->". company-select-last))
    (:map company-mode-map
      ("<tab>". tab-indent-or-complete)
      ("TAB". tab-indent-or-complete)))
    :config
    (setq
       company-minimum-prefix-length 1
       company-idle-delay 0.0
       company-tooltip-align-annotations t)

    (defun company-yasnippet-or-completion ()
     (interactive)
     (or (do-yas-expand)
       (company-complete-common)))

    (defun check-expansion ()
      (save-excursion
      (if (looking-at "\\_>") t
        (backward-char 1)
      (if (looking-at "\\.") t
        (backward-char 1)
      (if (looking-at "::") t nil)))))
     
    (defun do-yas-expand ()
      (let ((yas/fallback-behavior 'return-nil))
        (yas/expand)))
     
    (defun tab-indent-or-complete ()
      (interactive)
      (if (minibufferp)
          (minibuffer-complete)
      (if (or (not yas/minor-mode)
          (null (do-yas-expand)))
      (if (check-expansion)
          (company-complete-common)
        (indent-for-tab-command)))))

#+END_SRC
    
*** flycheck

    Flycheck, for on the fly syntax checking.

#+BEGIN_SRC emacs-lisp
  (use-package flycheck
  :ensure t)
#+END_SRC
    
*** snippets

#+BEGIN_SRC emacs-lisp
  (use-package yasnippet
    :ensure
    :config
    (yas-reload-all)
    (add-hook 'prog-mode-hook 'yas-minor-mode)
    (add-hook 'text-mode-hook 'yas-minor-mode))
#+END_SRC

*** lsp mode

    Configure language server support for syntax highlighting and code formatting.

#+BEGIN_SRC emacs-lisp
  (use-package lsp-mode
    :ensure
    :commands lsp
    :config
    (setq lsp-keymap-prefix "C-c l"
      lsp-modeline-diagnostics-enable t
      lsp-file-watch-threshold nil
      lsp-enable-file-watchers t
      lsp-print-performance nil
      lsp-log-io nil
      lsp-idle-delay 0.6
      lsp-eldoc-render-all t
      company-minimum-prefix-length 1
      company-idle-delay 0.0
      company-tooltip-align-annotations t
      lsp-rust-analyzer-cargo-watch-command "clippy"
      lsp-rust-analyzer-server-display-inlay-hints t
      lsp-rust-analyzer-server-command '("~/.cargo/bin/rustup run nightly rust-analyzer")
      lsp-rust-analyzer-proc-macro-enable t
      lsp-clangd-binary-path "/System/Volumes/Data/Library/Developer/CommandLineTools/usr/bin/clangd"
      lsp-go-gopls-server-path "~/.go/bin/gopls"
      lsp-pylsp-server-command "~/.pyenv/versions/emacs39/bin/pylsp")
    (lsp-register-custom-settings
     '(("gopls.completeUnimported" t t)
       ("gopls.staticcheck" t t)))
    (defun lsp-save-hooks ()
       (add-hook 'before-save-hook #'lsp-organize-imports t t))

    (with-eval-after-load 'lsp-mode
      (add-hook 'lsp-mode-hook #'lsp-enable-which-key-integration)))

  (use-package lsp-ui
     :ensure
     :commands lsp-ui-mode
     :config
     (setq lsp-ui-peek-always-show t
      lsp-ui-sideline-show-hover nil
      lsp-ui-doc-enable nil))
  (use-package lsp-ivy :commands lsp-ivy-workspace-symbol)
#+END_SRC

*** rust

    Enable rust mode, hook to lsp.

#+BEGIN_SRC emacs-lisp
  (use-package rustic
    :ensure
    :bind
      (:map rustic-mode-map
        ("M-j" . lsp-ui-imenu)
        ("M-?" . lsp-find-references)
        ("C-c C-c l" . flycheck-list-errors)
        ("C-c C-c a" . lsp-execute-code-action)
        ("C-c C-c r" . lsp-rename)
        ("C-c C-c q" . lsp-workspace-restart)
        ("C-c C-c Q" . lsp-workspace-shutdown)
        ("C-c C-c s" . lsp-rust-analyzer-status))
    :config
    ;; comment to disable rustfmt on save
    (setq rustic-format-on-save nil)
    :hook ((rustic-mode . rk/rustic-mode-hook)))

  (defun rk/rustic-mode-hook ()
    ;; so that run C-c C-c C-r works without having to confirm, but don't try to
    ;; save rust buffers that are not file visiting. Once
    ;; https://github.com/brotzeit/rustic/issues/253 has been resolved this should
    ;; no longer be necessary.
    (when buffer-file-name
      (setq-local buffer-save-without-query t)))
#+END_SRC

*** clang / c
    Enable clang for c support

#+BEGIN_SRC emacs-lisp
  (use-package lsp-mode
    :ensure t
    :hook (c-mode . lsp-deferred))
#+END_SRC

*** golang

    Enable go mode, hook to lsp.

#+BEGIN_SRC emacs-lisp
  (use-package go-mode
    :ensure t
    :hook ((go-mode . lsp-deferred)))
#+END_SRC
    
*** python

    Use python mode, hook to lsp.

#+BEGIN_SRC emacs-lisp
  (use-package python-mode
    :ensure t
    :hook ((python-mode . lsp-deferred)))
#+END_SRC
    
*** yaml

    Some YAML formatting configuration.

#+BEGIN_SRC emacs-lisp
  (use-package yaml-mode
    :ensure t
    :init
    (add-hook 'yaml-mode-hook
	(lambda ()
		(define-key yaml-mode-map "\C-m" 'newline-and-indent))))
#+END_SRC
** music!?
*** mpdel
#+BEGIN_SRC emacs-lisp
  (use-package mpdel
    :ensure t)

  (use-package ivy-mpdel
    :ensure t)
#+END_SRC
